storage: ../../.verdaccio/storage
plugins: ../../.verdaccio/plugins

listen:
  - 0.0.0.0:4873

web:
  title: Local Monorepo Registry

auth:
  htpasswd:
    file: ../../.verdaccio/htpasswd
    algorithm: bcrypt

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - type: stdout
    format: pretty
    level: http

