package expo.modules

import expo.modules.core.interfaces.Package
import expo.modules.kotlin.ModulesProvider
import expo.modules.kotlin.modules.Module

/**
 * Auto-generated by scripts/generate-native-kit-android.sh
 * Provides Expo Modules Core with the list of Kotlin modules and legacy packages.
 */
class ExpoModulesPackageList : ModulesProvider {
  override fun getModulesList(): List<Class<out Module>> =
    listOf(
      expo.modules.kotlin.defaultmodules.CoreModule::class.java,
      expo.modules.kotlin.defaultmodules.JSLoggerModule::class.java,
      expo.modules.kotlin.defaultmodules.NativeModulesProxyModule::class.java,
      com.vsco.nativekit.fileSystem.expo_modules_filesystem.FileSystemModule::class.java,
      com.vsco.nativekit.fileSystem.FileSystemNextModule::class.java,
    )

  companion object {
    @JvmStatic
    fun getPackageList(): List<Package> =
      listOf(
        com.vsco.nativekit.fileSystem.expo_modules_filesystem.FileSystemPackage(),
      )
  }
}
