// swift-tools-version:5.7
// VSCO Native Kit - Unified iOS SPM Package
// Generated from native dependencies detected in Verdaccio modules
// Compatible with React Native 0.81.5
import PackageDescription

let package = Package(
    name: "VSCONativeKit",
    platforms: [.iOS(.v14)],  // iOS 14.0+ required for React Native 0.81.5
    products: [
        .library(
            name: "VSCONativeKit",
            targets: ["VSCONativeKit"]
        ),
        .library(
            name: "VSCOCamera",
            targets: ["VSCOCamera"]
        ),
        .library(
            name: "VSCOExpoFileSystem",
            targets: ["VSCOExpoFileSystem"]
        ),
        .library(
            name: "VSCOExpoModulesCore",
            targets: ["VSCOExpoModulesCore"]
        ),
        .library(
            name: "VSCOSafeAreaContext",
            targets: ["VSCOSafeAreaContext"]
        ),
        .library(
            name: "VSCOSvg",
            targets: ["VSCOSvg"]
        )
    ],
    dependencies: [
        // React Native Runtime - required for React Native headers
        // Path is relative to this package's location (vsco-native-kit/ios/VSCONativeKit/)
        .package(path: "../../../frameworks/ios/VSCOReactNativeRuntime")
    ],
    targets: [
        .target(
            name: "VSCOCamera",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime")
            ],
            path: "Sources/VSCOCamera",
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("RCT"),
                .headerSearchPath("RN"),
                .headerSearchPath("RNCamera.xcodeproj")
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("RCT"),
                .headerSearchPath("RN"),
                .headerSearchPath("RNCamera.xcodeproj")
            ]
        ),
        .target(
            name: "VSCOExpoFileSystemObjC",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime"),
                .target(name: "VSCOExpoModulesCoreObjC")
            ],
            path: "Sources/VSCOExpoFileSystem",
            exclude: ["Tests"],  // Exclude Fabric (New Architecture) files and test files
            sources: ["EXFileSystemHandler.h",
                "ExpoFileSystem.h",
                "EXFileSystemLocalFileHandler.m",
                "EXFileSystemAssetLibraryHandler.m",
                "NSData+EXFileSystem.m",
                "EXFileSystemAssetLibraryHandler.h",
                "EXFileSystemLocalFileHandler.h",
                "NSData+EXFileSystem.h",
                "EXSessionTasks/EXSessionTaskDelegate.h",
                "EXSessionTasks/EXSessionUploadTaskDelegate.m",
                "EXSessionTasks/EXSessionResumableDownloadTaskDelegate.m",
                "EXSessionTasks/EXSessionTaskDispatcher.m",
                "EXSessionTasks/EXSessionHandler.h",
                "EXSessionTasks/EXTaskHandlersManager.m",
                "EXSessionTasks/EXSessionDownloadTaskDelegate.h",
                "EXSessionTasks/EXSessionCancelableUploadTaskDelegate.h",
                "EXSessionTasks/EXSessionUploadTaskDelegate.h",
                "EXSessionTasks/EXSessionTaskDelegate.m",
                "EXSessionTasks/EXSessionResumableDownloadTaskDelegate.h",
                "EXSessionTasks/EXTaskHandlersManager.h",
                "EXSessionTasks/EXSessionHandler.m",
                "EXSessionTasks/EXSessionTaskDispatcher.h",
                "EXSessionTasks/EXSessionCancelableUploadTaskDelegate.m",
                "EXSessionTasks/EXSessionDownloadTaskDelegate.m"
            ],
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("EXSessionTasks"),
                .headerSearchPath("Next"),
                .headerSearchPath("Tests"),
                .headerSearchPath("../VSCOExpoModulesCore")
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("EXSessionTasks"),
                .headerSearchPath("Next"),
                .headerSearchPath("Tests"),
                .headerSearchPath("../VSCOExpoModulesCore")
            ]
        ),
        .target(
            name: "VSCOExpoFileSystem",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime"),
                .target(name: "VSCOExpoFileSystemObjC"),
                .target(name: "VSCOExpoModulesCore")
            ],
            path: "Sources/VSCOExpoFileSystem",
            exclude: ["Tests"],  // Exclude Fabric (New Architecture) files and test files
            sources: ["FileSystemModule.swift",
                "Next/FileSystemNextModule.swift",
                "Next/FileSystemFileHandle.swift",
                "Next/FileSystemPath.swift",
                "Next/FileSystemDirectory.swift",
                "Next/FileSystemFile.swift",
                "Next/FileSystemNextExceptions.swift",
                "Encoding.swift",
                "FileSystemBackgroundSessionHandler.swift",
                "FileSystemRecords.swift",
                "FileSystemHelpers.swift",
                "FileSystemExceptions.swift",
                "NetworkingHelpers.swift"
            ]
        ),
        .target(
            name: "VSCOExpoModulesCoreObjC",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime")
            ],
            path: "Sources/VSCOExpoModulesCore",
            exclude: ["Fabric", "Tests", "TestUtils"],  // Exclude Fabric (New Architecture) files and test files
            sources: ["EXAppDefines.h",
                "ReactDelegates/EXReactDelegateWrapper.h",
                "ReactDelegates/EXReactDelegateWrapper.mm",
                "Core/ExpoBridgeModule.mm",
                "Core/ExpoBridgeModule.h",
                "Core/Modules/CoreModuleHelper.m",
                "Core/Modules/CoreModuleHelper.h",
                "Core/Views/SwiftUI/SwiftUIViewProps.h",
                "RCTComponentData+Privates.m",
                "Platform/Platform.h",
                "EXLegacyExpoViewProtocol.h",
                "Legacy/EXUtilities.m",
                "Legacy/EXExportedModule.h",
                "Legacy/EXUnimodulesCompat.h",
                "Legacy/EXSingletonModule.m",
                "Legacy/NativeModulesProxy/EXNativeModulesProxy.h",
                "Legacy/NativeModulesProxy/EXNativeModulesProxy.mm",
                "Legacy/ModuleRegistryAdapter/EXModuleRegistryAdapter.h",
                "Legacy/ModuleRegistryAdapter/EXModuleRegistryHolderReactModule.h",
                "Legacy/ModuleRegistryAdapter/EXModuleRegistryHolderReactModule.m",
                "Legacy/ModuleRegistryAdapter/EXModuleRegistryAdapter.m",
                "Legacy/ModuleRegistry/EXModuleRegistry.m",
                "Legacy/ModuleRegistry/EXModuleRegistryDelegate.h",
                "Legacy/ModuleRegistry/EXModuleRegistry.h",
                "Legacy/EXUtilities.h",
                "Legacy/EXSingletonModule.h",
                "Legacy/EXExportedModule.m",
                "Legacy/Protocols/EXUIManager.h",
                "Legacy/Protocols/EXEventEmitter.h",
                "Legacy/Protocols/EXLogHandler.h",
                "Legacy/Protocols/EXAppLifecycleListener.h",
                "Legacy/Protocols/EXEventEmitterService.h",
                "Legacy/Protocols/EXJavaScriptContextProvider.h",
                "Legacy/Protocols/EXUtilitiesInterface.h",
                "Legacy/Protocols/EXInternalModule.h",
                "Legacy/Protocols/EXAppLifecycleService.h",
                "Legacy/Protocols/EXModuleRegistryConsumer.h",
                "Legacy/Services/EXReactNativeAdapter.h",
                "Legacy/Services/EXReactLogHandler.m",
                "Legacy/Services/EXLogManager.m",
                "Legacy/Services/EXReactNativeEventEmitter.h",
                "Legacy/Services/Permissions/EXPermissionsService.m",
                "Legacy/Services/Permissions/EXReactNativeUserNotificationCenterProxy.h",
                "Legacy/Services/Permissions/EXReactNativeUserNotificationCenterProxy.m",
                "Legacy/Services/Permissions/EXPermissionsService.h",
                "Legacy/Services/EXReactLogHandler.h",
                "Legacy/Services/EXLogManager.h",
                "Legacy/Services/EXReactNativeAdapter.mm",
                "Legacy/Services/EXReactNativeEventEmitter.m",
                "Legacy/EXBridgeModule.h",
                "Legacy/ModuleRegistryProvider/EXModuleRegistryProvider.h",
                "Legacy/ModuleRegistryProvider/EXModuleRegistryProvider.m",
                "JSI/EXJavaScriptRuntime.mm",
                "JSI/EXJSIUtils.h",
                "JSI/EXJavaScriptSharedObjectBinding.h",
                "JSI/EXJSIUtils.mm",
                "JSI/EXJavaScriptObject.h",
                "JSI/EXJSIConversions.h",
                "JSI/EXSharedObjectUtils.h",
                "JSI/EXJavaScriptWeakObject.mm",
                "JSI/EXRawJavaScriptFunction.mm",
                "JSI/EXJavaScriptTypedArray.h",
                "JSI/EXJavaScriptWeakObject.h",
                "JSI/EXJSIInstaller.h",
                "JSI/ExpoModulesHostObject.mm",
                "JSI/EXJavaScriptValue.h",
                "JSI/ExpoModulesHostObject.h",
                "JSI/EXJavaScriptSharedObjectBinding.mm",
                "JSI/EXJavaScriptObject.mm",
                "JSI/EXJSIInstaller.mm",
                "JSI/EXJavaScriptRuntime.h",
                "JSI/EXSharedObjectUtils.mm",
                "JSI/EXJSIConversions.mm",
                "JSI/EXJavaScriptValue.mm",
                "JSI/EXStringUtils.h",
                "JSI/EXStringUtils.cpp",
                "JSI/EventEmitter.cpp",
                "JSI/JSIUtils.cpp",
                "JSI/LazyObject.cpp",
                "JSI/NativeModule.cpp",
                "JSI/ObjectDeallocator.cpp",
                "JSI/SharedObject.cpp",
                "JSI/SharedRef.cpp",
                "JSI/TypedArray.cpp",
                "JSI/EXRawJavaScriptFunction.h",
                "JSI/EXJavaScriptTypedArray.mm",
                "EXAppDefines.m",
                "RCTComponentData+Privates.h",
                "ExpoModulesCore.h",
                "Swift.h",
                "EXDefines.h",
                "Interfaces/Sensors/EXMagnetometerUncalibratedInterface.h",
                "Interfaces/Sensors/EXDeviceMotionInterface.h",
                "Interfaces/Sensors/EXMagnetometerInterface.h",
                "Interfaces/Sensors/EXAccelerometerInterface.h",
                "Interfaces/Sensors/EXBarometerInterface.h",
                "Interfaces/Sensors/EXGyroscopeInterface.h",
                "Interfaces/TaskManager/EXTaskLaunchReason.h",
                "Interfaces/TaskManager/EXTaskManagerInterface.h",
                "Interfaces/TaskManager/EXTaskConsumerInterface.h",
                "Interfaces/TaskManager/EXTaskInterface.h",
                "Interfaces/TaskManager/EXTaskServiceInterface.h",
                "Interfaces/Camera/EXCameraInterface.h",
                "Interfaces/Constants/EXConstantsInterface.h",
                "Interfaces/FaceDetector/EXFaceDetectorManagerInterface.h",
                "Interfaces/FaceDetector/EXFaceDetectorManagerProviderInterface.h",
                "Interfaces/FileSystem/EXFilePermissionModuleInterface.h",
                "Interfaces/FileSystem/EXFileSystemInterface.h",
                "Interfaces/Permissions/EXPermissionsMethodsDelegate.h",
                "Interfaces/Permissions/EXPermissionsInterface.h",
                "Interfaces/Permissions/EXPermissionsMethodsDelegate.m",
                "Interfaces/Permissions/EXUserNotificationCenterProxyInterface.h",
                "Interfaces/ImageLoader/EXImageLoaderInterface.h"
            ],
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("Api"),
                .headerSearchPath("AppDelegates"),
                .headerSearchPath("Core"),
                .headerSearchPath("Core/Modules"),
                .headerSearchPath("Core/Views"),
                .headerSearchPath("DevTools"),
                .headerSearchPath("FileSystemUtilities"),
                .headerSearchPath("Interfaces"),
                .headerSearchPath("Interfaces/Camera"),
                .headerSearchPath("Interfaces/Constants"),
                .headerSearchPath("Interfaces/FaceDetector"),
                .headerSearchPath("Interfaces/FileSystem"),
                .headerSearchPath("Interfaces/ImageLoader"),
                .headerSearchPath("Interfaces/Permissions"),
                .headerSearchPath("Interfaces/Sensors"),
                .headerSearchPath("Interfaces/TaskManager"),
                .headerSearchPath("JSI"),
                .headerSearchPath("Legacy"),
                .headerSearchPath("Legacy/ModuleRegistry"),
                .headerSearchPath("Legacy/ModuleRegistryAdapter"),
                .headerSearchPath("Legacy/ModuleRegistryProvider"),
                .headerSearchPath("Legacy/NativeModulesProxy"),
                .headerSearchPath("Legacy/Protocols"),
                .headerSearchPath("Legacy/Services"),
                .headerSearchPath("Platform"),
                .headerSearchPath("ReactDelegates"),
                .headerSearchPath("TestUtils"),
                .headerSearchPath("Tests"),
                .headerSearchPath("Uuidv5")
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("Api"),
                .headerSearchPath("AppDelegates"),
                .headerSearchPath("Core"),
                .headerSearchPath("Core/Modules"),
                .headerSearchPath("Core/Views"),
                .headerSearchPath("DevTools"),
                .headerSearchPath("FileSystemUtilities"),
                .headerSearchPath("Interfaces"),
                .headerSearchPath("Interfaces/Camera"),
                .headerSearchPath("Interfaces/Constants"),
                .headerSearchPath("Interfaces/FaceDetector"),
                .headerSearchPath("Interfaces/FileSystem"),
                .headerSearchPath("Interfaces/ImageLoader"),
                .headerSearchPath("Interfaces/Permissions"),
                .headerSearchPath("Interfaces/Sensors"),
                .headerSearchPath("Interfaces/TaskManager"),
                .headerSearchPath("JSI"),
                .headerSearchPath("Legacy"),
                .headerSearchPath("Legacy/ModuleRegistry"),
                .headerSearchPath("Legacy/ModuleRegistryAdapter"),
                .headerSearchPath("Legacy/ModuleRegistryProvider"),
                .headerSearchPath("Legacy/NativeModulesProxy"),
                .headerSearchPath("Legacy/Protocols"),
                .headerSearchPath("Legacy/Services"),
                .headerSearchPath("Platform"),
                .headerSearchPath("ReactDelegates"),
                .headerSearchPath("TestUtils"),
                .headerSearchPath("Tests"),
                .headerSearchPath("Uuidv5")
            ]
        ),
        .target(
            name: "VSCOExpoModulesCore",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime"),
                .target(name: "VSCOExpoModulesCoreObjC")
            ],
            path: "Sources/VSCOExpoModulesCore",
            exclude: ["Fabric", "Tests", "TestUtils"],  // Exclude Fabric (New Architecture) files and test files
            sources: ["Api/Factories/ModuleFactories.swift",
                "Api/Factories/ConstantFactories.swift",
                "Api/Factories/SyncFunctionFactories.swift",
                "Api/Factories/AsyncFunctionFactories.swift",
                "Api/Factories/ConcurrentFunctionFactories.swift",
                "Api/Factories/ObjectFactories.swift",
                "Api/Factories/EventListenersFactories.swift",
                "Api/Factories/ViewFactories.swift",
                "Api/Factories/PropertyFactories.swift",
                "Api/Factories/ClassFactories.swift",
                "Api/Builders/ObjectDefinitionBuilder.swift",
                "Api/Builders/ViewDefinitionBuilder.swift",
                "Api/Builders/ClassComponentBuilder.swift",
                "ReactDelegates/ExpoReactDelegate.swift",
                "ReactDelegates/ExpoReactDelegateHandler.swift",
                "Utilities.swift",
                "Core/ExpoRuntime.swift",
                "Core/Records/AnyField.swift",
                "Core/Records/Field.swift",
                "Core/Records/FieldExtensions.swift",
                "Core/Records/Record.swift",
                "Core/Records/FieldOption.swift",
                "Core/AppCodeSignEntitlements.swift",
                "Core/Conversions.swift",
                "Core/Classes/ClassRegistry.swift",
                "Core/Classes/AnyClassDefinitionElement.swift",
                "Core/Classes/ClassDefinition.swift",
                "Core/JavaScriptUtils.swift",
                "Core/MainValueConverter.swift",
                "Core/ModuleHolder.swift",
                "Core/ModuleRegistry.swift",
                "Core/Objects/PropertyDefinition.swift",
                "Core/Objects/JavaScriptObjectBuilder.swift",
                "Core/Objects/ConstantDefinition.swift",
                "Core/Objects/ObjectDefinition.swift",
                "Core/Exceptions/Exception.swift",
                "Core/Exceptions/GenericException.swift",
                "Core/Exceptions/CodedError.swift",
                "Core/Exceptions/ChainableException.swift",
                "Core/Exceptions/CommonExceptions.swift",
                "Core/Exceptions/ExceptionOrigin.swift",
                "Core/Exceptions/UnexpectedException.swift",
                "Core/ModulesProvider.swift",
                "ExpoModulesProvider.swift",
                "Core/SharedObjects/SharedObject.swift",
                "Core/SharedObjects/SharedRef.swift",
                "Core/SharedObjects/SharedObjectRegistry.swift",
                "Core/JSValueEncoder.swift",
                "Core/Promise.swift",
                "Core/DynamicTypes/DynamicVoidType.swift",
                "Core/DynamicTypes/DynamicEnumType.swift",
                "Core/DynamicTypes/DynamicEncodableType.swift",
                "Core/DynamicTypes/DynamicType.swift",
                "Core/DynamicTypes/DynamicDictionaryType.swift",
                "Core/DynamicTypes/DynamicValueOrUndefinedType.swift",
                "Core/DynamicTypes/DynamicSwiftUIViewType.swift",
                "Core/DynamicTypes/DynamicOptionalType.swift",
                "Core/DynamicTypes/AnyDynamicType.swift",
                "Core/DynamicTypes/DynamicDataType.swift",
                "Core/DynamicTypes/DynamicSharedObjectType.swift",
                "Core/DynamicTypes/DynamicStringType.swift",
                "Core/DynamicTypes/DynamicConvertibleType.swift",
                "Core/DynamicTypes/DynamicTypedArrayType.swift",
                "Core/DynamicTypes/DynamicRawType.swift",
                "Core/DynamicTypes/DynamicNumberType.swift",
                "Core/DynamicTypes/DynamicJavaScriptType.swift",
                "Core/DynamicTypes/DynamicArrayType.swift",
                "Core/DynamicTypes/DynamicViewType.swift",
                "Core/DynamicTypes/DynamicEitherType.swift",
                "Core/Functions/AnyFunctionDefinition.swift",
                "Core/Functions/AsyncFunctionDefinition.swift",
                "Core/Functions/SyncFunctionDefinition.swift",
                "Core/Functions/ConcurrentFunctionDefinition.swift",
                "Core/EventListener.swift",
                "Core/Convertibles/Convertibles+Color.swift",
                "Core/Convertibles/Convertibles+CMTime.swift",
                "Core/TypedArrays/TypedArray.swift",
                "Core/TypedArrays/GenericTypedArray.swift",
                "Core/TypedArrays/AnyTypedArray.swift",
                "Core/TypedArrays/ConcreteTypedArrays.swift",
                "Core/Events/EventObservingDefinition.swift",
                "Core/Events/LegacyEventEmitterCompat.swift",
                "Core/Events/Callback.swift",
                "Core/Events/EventDispatcher.swift",
                "Core/AppContext.swift",
                "Core/Modules/ModuleDefinitionBuilder.swift",
                "Core/Modules/JSLoggerModule.swift",
                "Core/Modules/ModuleDefinition.swift",
                "Core/Modules/CoreModule.swift",
                "Core/Modules/Module.swift",
                "Core/Views/ExpoView.swift",
                "Core/Views/UnimplementedExpoView.swift",
                "Core/Views/ComponentData.swift",
                "Core/Views/ConcreteViewProp.swift",
                "Core/Views/AppleView.swift",
                "Core/Views/AnyViewProp.swift",
                "Core/Views/ViewDefinition.swift",
                "Core/Views/ViewModuleWrapper.swift",
                "Core/Views/SwiftUI/ExpoSystemColors.swift",
                "Core/Views/SwiftUI/View+Modifiers.swift",
                "Core/Views/SwiftUI/ExpoSwiftUI.swift",
                "Core/Views/SwiftUI/SwiftUIViewDefinitionDefaultProps.swift",
                "Core/Views/SwiftUI/SwiftUIHostingView.swift",
                "Core/Views/SwiftUI/AnyChild.swift",
                "Core/Views/SwiftUI/SwiftUIVirtualView.swift",
                "Core/Views/SwiftUI/Convertibles+SwiftUI.swift",
                "Core/Views/SwiftUI/AutoSizingStack.swift",
                "Core/Views/SwiftUI/SwiftUIViewDefinition.swift",
                "Core/Views/SwiftUI/SwiftUIViewProps.swift",
                "Core/Views/SwiftUI/SwiftUILayoutMetrics.swift",
                "Core/Views/SwiftUI/SwiftUIShadowNodeProxy.swift",
                "Core/Views/SwiftUI/SwiftUIViewFrameObserver.swift",
                "Core/Views/SwiftUI/SwiftUIViewDefinitionBuilder.swift",
                "Core/Views/SwiftUI/SwiftUIViewHost.swift",
                "Core/Views/ViewLifecycleMethod.swift",
                "Core/AppContextConfig.swift",
                "Core/Protocols/AnyDefinition.swift",
                "Core/Protocols/AnyExpoView.swift",
                "Core/Protocols/AnyModule.swift",
                "Core/Protocols/AnyViewDefinition.swift",
                "Core/Logging/LoggerTimer.swift",
                "Core/Logging/Logger.swift",
                "Core/Logging/PersistentFileLog.swift",
                "Core/Logging/LogHandlers.swift",
                "Core/Logging/LogType.swift",
                "Core/Arguments/Either.swift",
                "Core/Arguments/AnyArgument.swift",
                "Core/Arguments/Convertible.swift",
                "Core/Arguments/Convertibles.swift",
                "Core/Arguments/Enumerable.swift",
                "Core/Arguments/ValueOrUndefined.swift",
                "Core/JavaScriptFunction.swift",
                "Platform/Platform.swift",
                "Platform/NSLabel.swift",
                "Legacy/NativeModulesProxy/NativeModulesProxyModule.swift",
                "JSI/JavaScriptRuntime.swift",
                "JSI/JavaScriptValue.swift",
                "Uuidv5/Exceptions.swift",
                "Uuidv5/Uuidv5.swift",
                "AppDelegates/ExpoAppDelegateSubscriberManager.swift",
                "AppDelegates/ExpoReactNativeFactoryProtocol.swift",
                "AppDelegates/ExpoAppDelegateSubscriberRepository.swift",
                "AppDelegates/ExpoAppDelegateSubscriber.swift",
                "AppDelegates/ReactNativeFactoryProvider.swift",
                "AppDelegates/ModulePriorities.swift",
                "FileSystemUtilities/FileSystemUtilities.swift",
                "FileSystemUtilities/FileSystemLegacyUtilities.swift"
            ]
        ),
        .target(
            name: "VSCOSafeAreaContext",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime")
            ],
            path: "Sources/VSCOSafeAreaContext",
            exclude: ["Fabric"],  // Exclude Fabric (New Architecture) files and test files - we use Legacy Architecture
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("RNSafeAreaContext.xcodeproj")
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("RNSafeAreaContext.xcodeproj")
            ]
        ),
        .target(
            name: "VSCOSvg",
            dependencies: [
                .product(name: "React", package: "VSCOReactNativeRuntime")
            ],
            path: "Sources/VSCOSvg",
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("Brushes"),
                .headerSearchPath("Elements"),
                .headerSearchPath("Filters"),
                .headerSearchPath("Filters/MetalCI"),
                .headerSearchPath("RNSVG.xcodeproj"),
                .headerSearchPath("Shapes"),
                .headerSearchPath("Text"),
                .headerSearchPath("Utils"),
                .headerSearchPath("ViewManagers"),
                .headerSearchPath("Stubs")
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("Brushes"),
                .headerSearchPath("Elements"),
                .headerSearchPath("Filters"),
                .headerSearchPath("Filters/MetalCI"),
                .headerSearchPath("RNSVG.xcodeproj"),
                .headerSearchPath("Shapes"),
                .headerSearchPath("Text"),
                .headerSearchPath("Utils"),
                .headerSearchPath("ViewManagers"),
                .headerSearchPath("Stubs")
            ],
            linkerSettings: [
                .linkedLibrary("c++")
            ]
        ),
        .target(
            name: "VSCONativeKit",
            dependencies: ["VSCOCamera", "VSCOExpoFileSystem", "VSCOExpoModulesCore", "VSCOSafeAreaContext", "VSCOSvg"],
            path: "Sources/VSCONativeKit",
            publicHeadersPath: "."
        )
    ]
)
